/**
 * AUTO-GENERATED.
 * DO NOT EDIT.
 *
 * Generated by:
 * scripts/build-content.js
 */
export const generatedContent = {
  "index": {
    "version": 1,
    "contentVersion": 1,
    "generatedAt": "2026-07-09T20:53:26.141Z",
    "generator": "scripts/build-content.js",
    "regularLessons": [
      "lesson-append-and-open-lines",
      "lesson-basic-movement",
      "lesson-change-word-cw",
      "lesson-counts-move-faster",
      "lesson-delete-basics",
      "lesson-delete-end-replace",
      "lesson-how-to-exit-ex-commands",
      "lesson-insert-mode",
      "lesson-line-bounds-0-and",
      "lesson-line-jumps",
      "lesson-search-backward",
      "lesson-search-forward",
      "lesson-search-navigation-n-n",
      "lesson-undo-redo",
      "lesson-word-movement",
      "lesson-yank-put-copy-paste"
    ],
    "practiceLessons": [
      "lesson-practice-backward-search-practice",
      "lesson-practice-basic-movement-practice",
      "lesson-practice-change-word-practice",
      "lesson-practice-delete-character-practice",
      "lesson-practice-delete-line-practice",
      "lesson-practice-delete-to-end-practice",
      "lesson-practice-delete-word-practice",
      "lesson-practice-ex-commands-practice",
      "lesson-practice-forward-search-practice",
      "lesson-practice-insert-mode-practice",
      "lesson-practice-line-boundary-practice",
      "lesson-practice-line-jump-practice",
      "lesson-practice-replace-character-practice",
      "lesson-practice-search-navigation-practice",
      "lesson-practice-undo-redo-practice",
      "lesson-practice-word-motion-practice",
      "lesson-practice-yank-and-paste-practice"
    ]
  },
  "lessons": {
    "lesson-append-and-open-lines": {
      "id": "lesson-append-and-open-lines",
      "version": 1,
      "name": "Append and Open Lines",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use a to append after cursor. Use o to open a new line below, and O to open above. Add a new line between the two lines that reads 'Inserted here'.",
      "initialContent": [
        "First line.",
        "Second line."
      ],
      "targetContent": [
        "First line.",
        "Inserted here",
        "Second line."
      ]
    },
    "lesson-basic-movement": {
      "id": "lesson-basic-movement",
      "version": 1,
      "name": "Basic Movement",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use h, j, k, l to move the cursor. Reach the target character '$'.",
      "initialContent": [
        "Move with h(left), j(down), k(up), l(right).",
        "Your cursor starts here.",
        "",
        "The goal is to navigate to the dollar sign.",
        "Practice moving around the text.",
        "Once you are comfortable, move to the '$'."
      ],
      "target": {
        "row": 5,
        "col": 39
      }
    },
    "lesson-change-word-cw": {
      "id": "lesson-change-word-cw",
      "version": 1,
      "name": "Change Word (cw)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use cw to change the word 'bad' into 'good'. Press Esc when done.",
      "initialContent": [
        "This is a bad example."
      ],
      "targetText": {
        "line": 0,
        "text": "This is a good example."
      }
    },
    "lesson-counts-move-faster": {
      "id": "lesson-counts-move-faster",
      "version": 1,
      "name": "Counts: Move Faster",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use a count with motions. Press 3 then w to jump three words and land on 'target'.",
      "initialContent": [
        "one two three target here"
      ],
      "target": {
        "row": 0,
        "col": 14
      }
    },
    "lesson-delete-basics": {
      "id": "lesson-delete-basics",
      "version": 1,
      "name": "Delete Basics",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use dd to delete the full middle line. Then use dw to remove the word 'mistake' on the last line. You can use x to delete a single character if needed.",
      "initialContent": [
        "Keep this line.",
        "Delete this entire line.",
        "Fix this mistake here."
      ],
      "targetContent": [
        "Keep this line.",
        "Fix this here."
      ]
    },
    "lesson-delete-end-replace": {
      "id": "lesson-delete-end-replace",
      "version": 1,
      "name": "Delete End & Replace",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use D to delete from cursor to end of line, then use r to replace the 'x' with '!'.",
      "initialContent": [
        "Keep this → remove from here to end",
        "Replace this x"
      ],
      "targetContent": [
        "Keep this → ",
        "Replace this !"
      ]
    },
    "lesson-how-to-exit-ex-commands": {
      "id": "lesson-how-to-exit-ex-commands",
      "version": 1,
      "name": "How to Exit (Ex Commands)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Type :q to quit, or :wq to write and quit. Press Enter after the command.",
      "initialContent": [
        "Welcome to VIM Master!",
        "Most searched question: how to exit Vim?",
        "Try typing :q and press Enter (or :wq)."
      ],
      "exCommands": [
        "q",
        "wq"
      ]
    },
    "lesson-insert-mode": {
      "id": "lesson-insert-mode",
      "version": 1,
      "name": "Insert Mode",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Press 'a' to append after the cursor. Type ' is awesome!' and press Esc to return to NORMAL mode.",
      "initialContent": [
        "VIM has multiple modes. You've been in NORMAL mode.",
        "Press 'a' to append after the cursor and start typing.",
        "When you're done, press 'Escape' to go back.",
        "Your task: complete the sentence below.",
        "Learning VIM"
      ],
      "targetText": {
        "line": 4,
        "text": "Learning VIM is awesome!"
      }
    },
    "lesson-line-bounds-0-and": {
      "id": "lesson-line-bounds-0-and",
      "version": 1,
      "name": "Line Bounds (0 and $)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use 0 to jump to start of line and $ to jump to end. Move to the last character of the first line.",
      "initialContent": [
        "Jump to the start and end of this line.",
        "Practice makes perfect."
      ],
      "target": {
        "row": 0,
        "col": 38
      }
    },
    "lesson-line-jumps": {
      "id": "lesson-line-jumps",
      "version": 1,
      "name": "Line Jumps",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use gg to go to the first line, and G to go to the last line. Go to the last character of the last line.",
      "initialContent": [
        "This is the first line. Use 'gg' to come here.",
        "...",
        "...",
        "...",
        "This is the last line. Use 'G' to jump here.",
        "The target is on the word 'here'."
      ],
      "target": {
        "row": 5,
        "col": 30
      }
    },
    "lesson-practice-backward-search-practice": {
      "id": "lesson-practice-backward-search-practice",
      "version": 1,
      "name": "Backward Search Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "search-backward"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use ?text to search backward, N to find previous. Search backward for 'start'.",
      "initialContent": [
        "Search backward for 'start' in this text.",
        "Use ?start and press Enter to search backward.",
        "Then use 'N' to find the previous occurrence.",
        "Navigate to the start word.",
        "The start is here: start",
        "Another start appears earlier: start"
      ],
      "target": {
        "row": 4,
        "col": 20
      }
    },
    "lesson-practice-basic-movement-practice": {
      "id": "lesson-practice-basic-movement-practice",
      "version": 1,
      "name": "Basic Movement Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "hjkl"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use h, j, k, l to move the cursor. Navigate to the target character '$'.",
      "initialContent": [
        "Practice basic movement with h(left), j(down), k(up), l(right).",
        "Your cursor starts here.",
        "",
        "The goal is to navigate to the dollar sign below.",
        "Practice moving around the text first.",
        "Once comfortable, move to the '$' target.",
        "Target: $"
      ],
      "target": {
        "row": 6,
        "col": 8
      }
    },
    "lesson-practice-change-word-practice": {
      "id": "lesson-practice-change-word-practice",
      "version": 1,
      "name": "Change Word Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "cw"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use cw to change words. Replace the wrong words with correct ones.",
      "initialContent": [
        "The wrong animal is a elephant",
        "I like to eat wrong food",
        "VIM is a wrong editor",
        "Programming is wrong activity"
      ],
      "targetContent": [
        "The best animal is a elephant",
        "I like to eat good food",
        "VIM is a great editor",
        "Programming is fun activity"
      ]
    },
    "lesson-practice-delete-character-practice": {
      "id": "lesson-practice-delete-character-practice",
      "version": 1,
      "name": "Delete Character Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "x"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use x to delete characters. Remove the X from 'Delete X this' and fix other typos.",
      "initialContent": [
        "Delete the X from this line: 'Delete X this'",
        "Use x to remove the X character",
        "Also fix: 'Fixx this typo'",
        "And: 'Removve extra letters'"
      ],
      "targetContent": [
        "Delete the  this",
        "Use x to remove the  character",
        "Also fix: 'Fix this typo'",
        "And: 'Remove extra letters'"
      ]
    },
    "lesson-practice-delete-line-practice": {
      "id": "lesson-practice-delete-line-practice",
      "version": 1,
      "name": "Delete Line Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "dd"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use dd to delete entire lines. Remove the marked lines.",
      "initialContent": [
        "Keep this line",
        "DELETE THIS LINE",
        "Keep this line too",
        "REMOVE THIS ONE TOO",
        "Keep this final line"
      ],
      "targetContent": [
        "Keep this line",
        "Keep this line too",
        "Keep this final line"
      ]
    },
    "lesson-practice-delete-to-end-practice": {
      "id": "lesson-practice-delete-to-end-practice",
      "version": 1,
      "name": "Delete to End Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "D"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use D to delete from cursor to end of line. Clean up the messy line endings.",
      "initialContent": [
        "Keep this part DELETE_FROM_HERE_TO_END",
        "Preserve this DELETE_REST_OF_LINE",
        "Save this text REMOVE_EVERYTHING_AFTER",
        "Maintain this DELETE_TO_FINISH"
      ],
      "targetContent": [
        "Keep this part",
        "Preserve this",
        "Save this text",
        "Maintain this"
      ]
    },
    "lesson-practice-delete-word-practice": {
      "id": "lesson-practice-delete-word-practice",
      "version": 1,
      "name": "Delete Word Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "dw"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use dw to delete words. Remove the extra words to clean up the sentences.",
      "initialContent": [
        "This is a very very long sentence with extra words.",
        "Remove unnecessary extra words from this line too.",
        "Delete unwanted unwanted repetitions here.",
        "Clean up this messy messy text.",
        "Final result should be clean sentences."
      ],
      "targetContent": [
        "This is a very long sentence with words.",
        "Remove unnecessary words from this line too.",
        "Delete unwanted repetitions here.",
        "Clean up this messy text.",
        "Final result should be clean sentences."
      ]
    },
    "lesson-practice-ex-commands-practice": {
      "id": "lesson-practice-ex-commands-practice",
      "version": 1,
      "name": "Ex Commands Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ex"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Practice ex-commands like :q to quit and :wq to write and quit. Type :q and press Enter.",
      "initialContent": [
        "This is a VIM lesson for ex-commands",
        "Ex-commands start with a colon (:)",
        "Common commands: :q (quit), :w (write), :wq (write and quit)",
        "Type :q and press Enter to complete this lesson"
      ],
      "targetText": {
        "line": 3,
        "text": "Type :q and press Enter to complete this lesson"
      }
    },
    "lesson-practice-forward-search-practice": {
      "id": "lesson-practice-forward-search-practice",
      "version": 1,
      "name": "Forward Search Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "search-forward"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use /text to search forward, n to find next. Search for 'target' and navigate to it.",
      "initialContent": [
        "Search for the word 'target' in this text.",
        "Use /target and press Enter to search.",
        "Then use 'n' to find the next occurrence.",
        "Navigate to the target word.",
        "The target is here: target",
        "Another target appears later: target"
      ],
      "target": {
        "row": 4,
        "col": 20
      }
    },
    "lesson-practice-insert-mode-practice": {
      "id": "lesson-practice-insert-mode-practice",
      "version": 1,
      "name": "Insert Mode Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ia"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Press 'i' to insert before cursor, 'a' to append after cursor. Type 'INSERTED' and 'APPENDED'.",
      "initialContent": [
        "VIM has multiple modes. You're in NORMAL mode now.",
        "Press 'i' to insert before cursor and type 'INSERTED'.",
        "Press 'a' to append after cursor and type 'APPENDED'.",
        "When done, press 'Escape' to return to NORMAL mode.",
        "Complete the sentence: Learning VIM"
      ],
      "targetText": {
        "line": 4,
        "text": "Learning VIM INSERTED APPENDED"
      }
    },
    "lesson-practice-line-boundary-practice": {
      "id": "lesson-practice-line-boundary-practice",
      "version": 1,
      "name": "Line Boundary Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "0$"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use 0 to go to start of line, $ to go to end of line. Practice moving between boundaries.",
      "initialContent": [
        "Start here and go to end with $",
        "Then return to start with 0",
        "Practice moving between line boundaries",
        "Use 0 for start, $ for end of each line"
      ],
      "target": {
        "row": 0,
        "col": 0
      }
    },
    "lesson-practice-line-jump-practice": {
      "id": "lesson-practice-line-jump-practice",
      "version": 1,
      "name": "Line Jump Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ggG"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use gg to go to the first line, and G to go to the last line. Go to the last character of the last line.",
      "initialContent": [
        "This is the first line. Use 'gg' to come here.",
        "Second line",
        "Third line",
        "Fourth line",
        "This is the last line. Use 'G' to jump here.",
        "The target is the last character of this line."
      ],
      "target": {
        "row": 5,
        "col": 30
      }
    },
    "lesson-practice-replace-character-practice": {
      "id": "lesson-practice-replace-character-practice",
      "version": 1,
      "name": "Replace Character Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "r"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use r to replace single characters. Fix the typos by replacing wrong characters.",
      "initialContent": [
        "Thxs is a test",
        "VxM is awesome",
        "Reylace characters",
        "Fxx typos quickly"
      ],
      "targetContent": [
        "This is a test",
        "VIM is awesome",
        "Replace characters",
        "Fix typos quickly"
      ]
    },
    "lesson-practice-search-navigation-practice": {
      "id": "lesson-practice-search-navigation-practice",
      "version": 1,
      "name": "Search Navigation Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "nN"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "First search for 'word', then use n to go to next match, N to go to previous match. Navigate to the 3rd occurrence.",
      "initialContent": [
        "Find the word in this text",
        "Another word appears here",
        "The third word is the target",
        "More word instances follow",
        "Final word at the end"
      ],
      "target": {
        "row": 2,
        "col": 10
      }
    },
    "lesson-practice-undo-redo-practice": {
      "id": "lesson-practice-undo-redo-practice",
      "version": 1,
      "name": "Undo Redo Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "undo-redo"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Make some changes, then use u to undo them, and Ctrl+r to redo. Practice the undo/redo cycle.",
      "initialContent": [
        "Original text that will be modified",
        "Change this line and then undo it",
        "Practice undoing and redoing changes",
        "Master the undo/redo workflow"
      ],
      "target": {
        "row": 0,
        "col": 0
      }
    },
    "lesson-practice-word-motion-practice": {
      "id": "lesson-practice-word-motion-practice",
      "version": 1,
      "name": "Word Motion Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "wbe"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use w (next word), b (back), e (end of word). Get to the end of the 'destination' word.",
      "initialContent": [
        "Jumping between words is much faster than character by character.",
        "Use 'w' to jump forwards to the start of the next word.",
        "Use 'b' to jump backwards to the start of the previous word.",
        "Use 'e' to jump to the end of the current word.",
        "Find the ultimate destination."
      ],
      "target": {
        "row": 4,
        "col": 28
      }
    },
    "lesson-practice-yank-and-paste-practice": {
      "id": "lesson-practice-yank-and-paste-practice",
      "version": 1,
      "name": "Yank and Paste Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "yyp"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use yy to yank (copy) a line, then p to paste it. Duplicate the important lines.",
      "initialContent": [
        "This line should be duplicated",
        "",
        "This line should also be duplicated",
        "",
        "Don't duplicate this line"
      ],
      "targetContent": [
        "This line should be duplicated",
        "This line should be duplicated",
        "",
        "This line should also be duplicated",
        "This line should also be duplicated",
        "",
        "Don't duplicate this line"
      ]
    },
    "lesson-search-backward": {
      "id": "lesson-search-backward",
      "version": 1,
      "name": "Search Backward (?)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Press ? then type 'alpha' and Enter, then press N once to jump to the previous occurrence.",
      "initialContent": [
        "alpha beta gamma",
        "delta epsilon alpha",
        "zeta eta theta"
      ],
      "target": {
        "row": 0,
        "col": 0
      }
    },
    "lesson-search-forward": {
      "id": "lesson-search-forward",
      "version": 1,
      "name": "Search Forward (/)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Press / then type 'target' and Enter, then press n once to jump to the next occurrence.",
      "initialContent": [
        "find the target here",
        "another target and another target",
        "no match on this line"
      ],
      "target": {
        "row": 1,
        "col": 27
      }
    },
    "lesson-search-navigation-n-n": {
      "id": "lesson-search-navigation-n-n",
      "version": 1,
      "name": "Search Navigation (n/N)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Search for 'foo' with /foo then press n twice to reach the third occurrence.",
      "initialContent": [
        "foo bar baz",
        "qux foo quux",
        "corge grault foo"
      ],
      "target": {
        "row": 2,
        "col": 13
      }
    },
    "lesson-undo-redo": {
      "id": "lesson-undo-redo",
      "version": 1,
      "name": "Undo / Redo",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Delete the middle line with dd, undo it with u, then redo with Ctrl+r to finish with the line deleted.",
      "initialContent": [
        "Top line.",
        "Remove me.",
        "Bottom line."
      ],
      "targetContent": [
        "Top line.",
        "Bottom line."
      ]
    },
    "lesson-word-movement": {
      "id": "lesson-word-movement",
      "version": 1,
      "name": "Word Movement",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use w (next word), b (back), e (end of word). Get to the end of the 'destination' word.",
      "initialContent": [
        "Jumping between words is much faster.",
        "Use 'w' to jump forwards to the start of the next word.",
        "Use 'b' to jump backwards to the start of the previous word.",
        "Use 'e' to jump to the end of the current word.",
        "Find the ultimate destination."
      ],
      "target": {
        "row": 4,
        "col": 28
      }
    },
    "lesson-yank-put-copy-paste": {
      "id": "lesson-yank-put-copy-paste",
      "version": 1,
      "name": "Yank & Put (Copy/Paste)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": []
      },
      "instructions": "Use yy to yank (copy) a line and p to put (paste) it. Duplicate the second line.",
      "initialContent": [
        "Let's copy and paste.",
        "Yank this line!",
        "And put it below this line.",
        ""
      ],
      "targetContent": [
        "Let's copy and paste.",
        "Yank this line!",
        "And put it below this line.",
        "Yank this line!"
      ]
    }
  }
};
